apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-staging
  template:
    metadata:
      labels:
        app: guestbook-ui-staging
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui-staging
        ports:
        - containerPort: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
